### ISSUE TITLE
About the 4th Test

### ISSUE THREAD

**Issue by FanxuMeng** [maxwelld90/tango_with_django_2_code#6]
Sorry for doing the actions so late. I figured out where is the problem for can't pass the test even the page shows the correct content. The HTML code for showing the picture has to be exactly same as 
  
**`<img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />`**

No **SPACE** or **LINE BREAK** is allowed 😵

_I personally think that maybe a little bit too harsh for people who need to pass the test to get the grade like university students. I wish it can be changed to a more friendly test_ : ) 😄

**Comment by maxwelld90** [comment]
Hi @FanxuMeng,

Okay. Yeah -- it does. The whole point of these tests is that you need to write the code _exactly_ as it appears in the book. Why? Because when you get a job as a developer and are given some module to write, you need to comply with the specification as it is given. It you don't, then your module might do something that is unexpected (according to the specification you are given), and might break the system it is part of!

However, I also get and accept that this can be considered a little harsh (from your point of view). Given that the HTML specification does allow linebreaks between attributes, maybe I can look into this in the future.

Given that the book does provide you with an example of what you needed to provide, I'll leave it for now, but will add it to the list for a future update. Can you help me though: _how exactly did you have this line of code when the test was failing?_ I would very much like to see what you did -- and if I can see that, maybe I can add a clarifying remark in the book.

Cheers,
David

**Comment by maxwelld90** [comment]
🤷‍♂️
